name: Test & Publish to PowerShell Gallery

on:
  push:
    tags:
      - "v*" # Pubblica solo quando fai un tag tipo v1.0.0

#  workflow_dispatch:
#    inputs:
#      modulePath:
#        description: "Provide the module path that includes .psd1"
#        required: true
#      NuGetApiKey:
#        description: "Provide NuGetApiKey for your profile in PSGallery."
#        required: true

jobs:
  publish_module:
    # The type of runner that the job will run on
    runs-on:
      windows-latest
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish module on PsGallery
        uses: aammirmirza/Publish2PSGallery@PSGallery_v2
        with:
          NuGetApiKey: ${{ secrets.PowerShellGalleryApiKey }}
          modulePath: ./
